package io.kalo.manager;

import io.kalo.content.Content;
import io.kalo.content.ContentType;
import io.kalo.content.ContentsPack;
import io.kalo.content.feature.event.ResourcePackGenerationEvent;
import io.kalo.event.AsyncResourcePackGenerationEvent;
import io.kalo.pack.PackFormats;
import io.kalo.pack.PackMeta;
import io.kalo.pack.ResourcePack;
import io.kalo.pack.ResourcePackImpl;
import io.kalo.pack.Writable;
import io.kalo.pack.ZipPackWriter;
import io.kalo.registry.Registries;
import io.kalo.platform.bedrock.BedrockPackCompiler;
import io.kalo.platform.bedrock.BedrockPackWriter;
import io.kalo.pack.PackMeta;
import io.kalo.utils.Constants;
import io.kalo.utils.Files;
import it.unimi.dsi.fastutil.Pair;
import org.bukkit.Bukkit;
import org.jetbrains.annotations.NotNull;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.logging.Level;
import java.util.logging.Logger;

public final class ResourcePackManagerImpl implements ResourcePackManager, Managerial, Reloadable {
    private static final Logger LOGGER = Logger.getLogger(ResourcePackManagerImpl.class.getName());

    private static final String PACK_DESCRIPTION = "Generated by " + Constants.PLUGIN_NAME;

    @Override
    public void preload(@NotNull Context context) {
    }

    @Override
    public void start(@NotNull Context context) {
        generateResourcePack();
    }

    @Override
    public void end(@NotNull Context context) {
    }

    @Override
    public @NotNull CompletableFuture<Void> generateResourcePack() {
        return CompletableFuture.runAsync(() -> {
            LOGGER.info("Generating resource pack...");

            ResourcePack resourcePack = new ResourcePackImpl(
                    PackMeta.of(PackFormats.CURRENT, PACK_DESCRIPTION));

            copyPackAssets(resourcePack);
            compileContentTypes(resourcePack);

            generateBedrockPack(resourcePack);

            RegistryManager.GlobalRegistries.registries().item().forEach(content ->
                    content.featureEventBus().call(new ResourcePackGenerationEvent(resourcePack)));

            Bukkit.getPluginManager().callEvent(new AsyncResourcePackGenerationEvent(resourcePack));

            try {
                ZipPackWriter.write(generatedPackFile(), resourcePack);
            } catch (Exception e) {
                LOGGER.log(Level.SEVERE, "Failed to write the generated resource pack", e);
                return;
            }

            LOGGER.info("Successfully generated resource pack (" + resourcePack.files().size() + " files)");
        }).exceptionally(throwable -> {
            // CompletableFuture swallows exceptions unless something joins the future,
            // and nothing does — without this a generation failure would be invisible.
            LOGGER.log(Level.SEVERE, "Resource pack generation failed", throwable);
            return null;
        });
    }

    private static @NotNull File generatedPackFile() {
        return new File(Constants.dataFolder(), "generated.zip");
    }

    /**
     * Builds the Bedrock pack and Geyser mapping alongside the Java pack.
     *
     * <p>The Java pack is passed in as a texture source only. A Bedrock pack has its own
     * layout and ignores the {@code assets/} tree entirely, so it gets its own container
     * rather than a copy of the Java one.</p>
     */
    private static void generateBedrockPack(@NotNull ResourcePack javaPack) {
        Registries registries = RegistryManager.GlobalRegistries.registries();

        ResourcePack bedrock = new ResourcePackImpl(PackMeta.of(0, PACK_DESCRIPTION));
        BedrockPackCompiler compiler = new BedrockPackCompiler(javaPack, bedrock);

        // One compiler across every content type: writing the manifest and mapping per
        // type meant the last one to run erased the others' mappings.
        compiler.add(registries.item());
        compiler.add(registries.armor());

        BedrockPackCompiler.Result result = compiler.finish();

        try {
            BedrockPackWriter.write(new File(Constants.dataFolder(), "generated.mcpack"), result.pack().files());
            java.nio.file.Files.write(new File(Constants.dataFolder(), "bedrock-mappings.json").toPath(),
                    result.mappings().toByteArray());
        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "Failed to write Bedrock output", e);
            return;
        }

        LOGGER.info("Successfully generated Bedrock pack (" + result.pack().files().size() + " files, "
                + result.mappedCount() + " mapped vanilla items)");
        if (result.skippedCount() > 0) {
            // Said out loud rather than silently dropped: a pack author who sees their
            // item on Java but not on Bedrock deserves to know why.
            LOGGER.warning(result.skippedCount() + " item(s) were left out of the Bedrock pack because they use a "
                    + "custom model; Bedrock geometry conversion is not implemented yet");
        }
    }

    /**
     * Copies each pack's {@code assets/} directory into the generated pack under its own
     * namespace, so textures and hand-authored models ship alongside generated JSON.
     */
    private static void copyPackAssets(@NotNull ResourcePack resourcePack) {
        for (Pair<net.kyori.adventure.key.Key, ContentsPack> entry
                : RegistryManager.GlobalRegistries.registries().contentsPacks().entries()) {
            ContentsPack pack = entry.value();
            File assetsFolder = new File(pack.packFolder(), "assets");
            if (!assetsFolder.isDirectory()) {
                continue;
            }

            for (File asset : Files.listFilesRecursively(assetsFolder)) {
                String relative = assetsFolder.toPath().relativize(asset.toPath()).toString().replace('\\', '/');
                resourcePack.file("assets/" + pack.id() + "/" + relative, Writable.file(asset));
            }
        }
    }

    /** Lets every registered content type contribute its own assets. */
    @SuppressWarnings("unchecked")
    private static void compileContentTypes(@NotNull ResourcePack resourcePack) {
        for (Pair<net.kyori.adventure.key.Key, ContentType<?>> entry
                : RegistryManager.GlobalRegistries.registries().types().entries()) {
            ContentType<Content> type = (ContentType<Content>) entry.value();

            List<Content> contents = new ArrayList<>();
            Registries registries = RegistryManager.GlobalRegistries.registries();
            for (Content content : type.contents(registries)) {
                if (type.clazz().isInstance(content)) {
                    contents.add(content);
                }
            }

            if (!contents.isEmpty()) {
                type.compilePack(resourcePack, contents);
            }
        }
    }
}
