package io.kalo.platform.bedrock;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import io.kalo.content.item.Item;
import io.kalo.content.item.definition.ItemDefinition;
import io.kalo.content.item.definition.ModelDefinition;
import io.kalo.pack.Json;
import io.kalo.pack.ResourcePack;
import io.kalo.pack.Writable;
import org.bukkit.Material;
import org.jetbrains.annotations.NotNull;

import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.TreeMap;
import java.util.UUID;

/** Compiles the shared IR into the Geyser v2 mapping and a Bedrock resource pack. */
public final class BedrockPackCompiler {
    private BedrockPackCompiler() {}

    public static void compile(@NotNull ResourcePack pack, @NotNull Iterable<? extends Item> items) {
        JsonObject textureData = new JsonObject();
        JsonObject mappings = new JsonObject();
        mappings.addProperty("format_version", 2);
        JsonObject mappedItems = new JsonObject();
        mappings.add("items", mappedItems);

        for (Item item : items) {
            ItemDefinition definition = item.definition();
            if (!definition.bedrock().enabled() || definition.model() instanceof ModelDefinition.Vanilla) continue;

            String bedrockId = definition.key().namespace() + ":" + definition.key().value();
            String javaItem = "minecraft:" + definition.java().baseMaterial().name().toLowerCase();
            String model = definition.key().asString();

            JsonObject mapping = new JsonObject();
            mapping.addProperty("type", "definition");
            mapping.addProperty("model", model);
            mapping.addProperty("bedrock_identifier", bedrockId);
            if (definition.display().name() != null) {
                mapping.addProperty("display_name", definition.key().asString());
            }
            JsonObject components = new JsonObject();
            components.addProperty("minecraft:max_stack_size", definition.behaviour().maxStackSize());
            mapping.add("components", components);

            JsonArray definitions = mappedItems.has(javaItem)
                    ? mappedItems.getAsJsonArray(javaItem) : new JsonArray();
            definitions.add(mapping);
            mappedItems.add(javaItem, definitions);

            String icon = definition.bedrock().iconOverride() != null
                    ? definition.bedrock().iconOverride() : definition.key().value();
            JsonObject texture = new JsonObject();
            JsonArray paths = new JsonArray();
            paths.add("textures/items/" + icon);
            texture.add("textures", paths);
            textureData.add(bedrockId, texture);

            // Sprite assets are copied from the Java pack into Bedrock's flat item atlas.
            if (definition.model() instanceof ModelDefinition.Sprite sprite) {
                String source = "assets/" + sprite.texture().namespace() + "/textures/"
                        + sprite.texture().value() + ".png";
                Writable sourceFile = pack.file(source);
                if (sourceFile != null) {
                    pack.file("textures/items/" + icon + ".png", sourceFile);
                }
            }
        }

        JsonObject itemTexture = new JsonObject();
        itemTexture.addProperty("resource_pack_name", "kalo");
        itemTexture.addProperty("texture_name", "atlas.items");
        itemTexture.add("texture_data", textureData);
        pack.file("textures/item_texture.json", Json.writable(itemTexture));
        pack.file("kalo-mappings.json", Json.writable(mappings));
        pack.file("manifest.json", Json.writable(manifest()));
    }

    private static @NotNull JsonObject manifest() {
        JsonObject header = new JsonObject();
        header.addProperty("name", "Kalo Bedrock Content");
        header.addProperty("description", "Generated by Kalo");
        header.addProperty("uuid", UUID.nameUUIDFromBytes("kalo-bedrock-header".getBytes(StandardCharsets.UTF_8)).toString());
        header.addProperty("version", "1.0.0");

        JsonObject module = new JsonObject();
        module.addProperty("type", "resources");
        module.addProperty("uuid", UUID.nameUUIDFromBytes("kalo-bedrock-module".getBytes(StandardCharsets.UTF_8)).toString());
        module.addProperty("version", "1.0.0");

        JsonArray modules = new JsonArray();
        modules.add(module);
        JsonObject manifest = new JsonObject();
        manifest.addProperty("format_version", 2);
        manifest.add("header", header);
        manifest.add("modules", modules);
        return manifest;
    }
}
